config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords', :omniauth_callbacks => "users/omniauth_callbacks"}  
  #devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
  end

  root "posts#index"

  #get 'search' => 'search#index', as: :search
  
end
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogruby</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <div id="sidebar">
    <div id="logo">

      <%= link_to root_path do %>
        <%= image_tag "1-freepik.jpg"%>
      <% end %>
    </div>
    
    <ul>
      <li class="category">Website</li>
      <li><%= link_to "Blog", root_path %></li>
      <li><%= link_to "About" %></li>
    </ul>

    <ul>
      <li class="category">Social</li>
      <li><a href="#">Twitter</a></li>
      <li><a href="#">Instagram</a></li>
      <li><a href="#">Github</a></li>
      <li><a href="#">Email</a></li>
    </ul>

  
      <!--<p class="sign_in"><%#= link_to "Admin Login" %></p>-->
  
  </div>

  <div id="main_content">
    <div id="header">
      <% if current_page?(root_path) %>
        <p>All Posts</p>
      <% else %>      
        <%= link_to "Back to All Posts", root_path %>
      <% end %>

      
    
      <% if user_signed_in? %>
        <div class="buttons">
          <%= link_to "New Post", new_post_path, class: "button" %>
          <%= link_to "Edit Profile", edit_user_registration_path, class: "button" %>
          <%= link_to "Log Out", destroy_user_session_path, class: "button" %>
        </div>
      <% elsif %>
        <div class="buttons">
          <%= link_to "Log In", new_user_session_path, class: "button" %>
        </div>
      <% end %>
    </div>
    
     <%#= if current_page?(root_path) || current_page?(post_path) %>
       <!-- <div class="search"> -->
        <!-- :title la truong du lieu trong db can tim -->
      <%#= search_form_for @search do |f| %>
          <%#= f.search_field :title_cont %>
          <%#= f.search_field :title_cont %>
          <%#= f.submit %>
        <%# end %>
        <!-- </div> -->
      <%# end %>

      <!--  <div class="search">
          <%#= form_tag search_path, method: :get do%>
            <%#= text_field_tag :q, nil %>
            <%#= text_field_tag :a, nil %>  
          <%#= submit_tag 'Search'%>            
          <%# end %>
        </div> -->
    
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert") %>
    <% end %>

    <%= yield %>
    
</div>
  </body>
</html>